### ISSUE TITLE
The access database can be changed from outside.

### ISSUE THREAD

**Issue by ghost** [etherisc/flightDelay#10]
https://etherscan.io/tx/0xb0705844b4b6aef522a8adf83e0e257578f577597771d8255241dc6d240ade54

See the transaction I've made?
I initially wanted to try giving myself a permission to withdraw the funds, but that seems too hard to do and I'm not into stealing coins (I did manage to change the database though).

**Comment by ptsteadman** [comment]
Hi @SopaXorzTaker, as far as I understand, being able to change permissions as you did in that transaction would not enable you to withdraw funds from the ledger contract.

If a non-privileged account calls `setPermissionById` or `setPermissionByAddress` on the [AccessController](https://github.com/etherisc/flightDelay/blob/master/contracts/FlightDelayAccessController.sol), it calls the `setAccessControl` method of [Database](https://github.com/etherisc/flightDelay/blob/master/contracts/FlightDelayDatabase.sol) with the first parameter (`_contract`) set to `msg.sender`, which in the context of `AccessController` is the non-privileged account address.

```
    function setAccessControl(address _contract, address _caller, uint8 _perm, bool _access) {
        // one and only hardcoded accessControl
        require(msg.sender == FD_CI.getContract("FD.AccessController"));
        accessControl[_contract][_caller][_perm] = _access;
    }

    function getAccessControl(address _contract, address _caller, uint8 _perm) returns (bool _allowed) {
        _allowed = accessControl[_contract][_caller][_perm];
    }
```

So if `0xf00` calls `setPermissionByAddress(0x66, 0xf00)`, (0x66 being the send funds permission), the accessControl data structure will be set like: `accessControl[0xf00][0xf00][0x66][true]`. The require check passes because the method has been called from AccessController contract.

If `0xf00` later attempts to send funds to itself using the [Ledger](https://github.com/etherisc/flightDelay/blob/master/contracts/FlightDelayLedger.sol) contract, the contract executes
`require(FD_AC.checkPermission(102, msg.sender));`,  which might seem promising until one looks at the AccessController `checkPermission` method:         
```
    function checkPermission(uint8 _perm, address _addr) returns (bool _success) {
        _success = FD_DB.getAccessControl(msg.sender, _addr, _perm);
    }
```

When `getAccessControl` is called, `msg.sender` is the Ledger contract, and the database has `accessControl[0xf00][0xf00][0x66][true]`, not `accessControl[(ledger contract address)][0xf00][0x66][true]`.
